# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f460633764b7b506c3d42019a4b2b00c55df0d89cc05e88229b69a17a4f614796e3692f6c860e07135af614e5f3c6ec7af905197e5b141458abf6b3a2e38903

test:
  secret_key_base: 07f3a18485c4937b2661b3dc78839b5fe528f64bea7672994db8356b94921c4734d704e488fdb21ed0c608a9d977a52821dc0f7c5338ca7e7f31cd6e923758d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
